---
new_page_extension: md
auto_deploy: false
admin_path: exampleSite/static/admin
webhook_url: https://api.stackbit.com/project/5dea44b7358efa001ab1b570/webhook/forestry
sections:
- type: document
  path: exampleSite/config.toml
  label: Config
  templates:
  - config
- type: document
  path: exampleSite/content/_index.md
  label: Home
  templates:
  - home
- type: document
  path: exampleSite/content/404/_index.md
  label: '404'
  templates:
  - pagenotfound
- type: directory
  path: exampleSite/content
  label: Basic Page
  create: all
  match: "*.md"
  exclude: "{_index.md,_index.md}"
  templates:
  - basicpage
- type: directory
  path: exampleSite/content/services
  label: Service
  create: all
  match: "**/*"
  exclude: "{_index.md,services/_index.md}"
  templates:
  - service
- type: document
  path: exampleSite/content/services/_index.md
  label: Services Overview
  templates:
  - services
- type: directory
  path: exampleSite/content/team
  label: Team
  create: all
  match: "**/*"
  exclude: "{_index.md,team/_index.md}"
  templates:
  - team
- type: document
  path: exampleSite/content/team/_index.md
  label: Team Overview
  templates:
  - teams
upload_dir: exampleSite/static/images
public_path: "/images"
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
build:
  preview_output_directory: public
  install_dependencies_command: npm install
  preview_docker_image: node:10
  mount_path: "/srv"
  instant_preview_command: npm run forestry:preview
